### ISSUE TITLE
Peer-to-peer code review 31/08/2021

### ISSUE THREAD

**Issue by ad9311** [Felipeg005/Leaderboard#2]
Good job Felipe, keep it up! 👍🏽

**Comment by Hamzaoutdoors** [comment]
# Congrats Felip 🥇 

>> your work is so structured and I like that you take the opportunity to practice what you learned

**Comment by DanSam5K** [comment]
- Good job @Felipeg005, You went the extra mile to ensure a fast start to your project 👏
